Repository mozilla/application-services, pull requests merged in 2018-07, with the labels that each got.

#100 Run sync methods in the same thread
  fxa-rust-client/sdks/swift/FxAClient/FxAClient/FirefoxAccount.swift
Labels: fxa-client

#104 Retire "boxlocker", use fxa-rust-client for the sync15-adapter example.
  Cargo.toml
  README.md
  boxlocker/.gitignore
  boxlocker/Cargo.toml
  boxlocker/README.md
  boxlocker/boxlocker.py
  boxlocker/requirements.txt
  boxlocker/src/main.rs
  sync15-adapter/Cargo.toml
  sync15-adapter/examples/sync-pass.rs
Labels: in progress

#90 Implement persist callback
  fxa-rust-client/ffi/src/lib.rs
  fxa-rust-client/sdks/swift/FxAClient/FxAClient/FirefoxAccount.swift
  fxa-rust-client/sdks/swift/FxAClient/FxAClient/fxa.h
  fxa-rust-client/src/lib.rs
  sandvich-ios/Example/FxAView.swift
Labels: WIP

#56 Initial port of Sync and TPS docs
  docs/assets/fxa-states.graffle
  docs/assets/fxa-states.pdf
  docs/assets/sync-states.graffle
  docs/assets/sync-states.pdf
  docs/sync/canned-bug-responses.md
  docs/sync/extension-storage.md
  docs/sync/faq.md
  docs/sync/file-desktop-bug.md
  docs/sync/redash.md
  docs/sync/state-machines.md
  docs/sync/tps.md
  docs/sync/welcome.md
  website/core/Footer.js
  website/i18n/en.json
  website/package.json
  website/pages/en/index.js
  website/sidebars.json
  website/static/css/custom.css
Labels: review
