Repository mozilla/application-services, pull requests merged in 2019-02, with the labels that each got.

#602 Start on re-organizing the docs
  CHANGELOG.md
  README.md
  docs/README.md
  docs/doc1.md
  docs/howtos/building-a-rust-component.md
  docs/howtos/consuming-rust-components-on-android.md
  docs/howtos/consuming-rust-components-on-ios.md
  docs/howtos/cut-a-new-release.md
  docs/howtos/exposing-rust-components-to-kotlin.md
  docs/howtos/setup-android-build-environment.md
  docs/howtos/signing-android-applications.md
  docs/howtos/working-with-reference-browser.md
  docs/product-portal/accounts/50000-most-common-passwords.md
  docs/product-portal/accounts/dev-process.md
  docs/product-portal/accounts/end-to-end-encryption.md
  docs/product-portal/accounts/faq.md
  docs/product-portal/accounts/fxa-client-android.md
  docs/product-portal/accounts/fxa-client-ios.md
  docs/product-portal/accounts/local-development.md
  docs/product-portal/accounts/metrics.md
  docs/product-portal/accounts/project-details.md
  docs/product-portal/accounts/welcome.md
  docs/product-portal/applications/consuming-megazord-libraries.md
  docs/product-portal/applications/welcome.md
  docs/product-portal/assets/fxa-states.graffle
  docs/product-portal/assets/fxa-states.pdf
  docs/product-portal/assets/push_architecture.svg
  docs/product-portal/assets/sync-states.graffle
  docs/product-portal/assets/sync-states.pdf
  docs/product-portal/push/design.md
  docs/product-portal/push/development.md
  docs/product-portal/push/history.md
  docs/product-portal/push/welcome.md
  docs/product-portal/sync/canned-bug-responses.md
  docs/product-portal/sync/extension-storage.md
  docs/product-portal/sync/faq.md
  docs/product-portal/sync/file-desktop-bug.md
  docs/product-portal/sync/redash.md
  docs/product-portal/sync/state-machines.md
  docs/product-portal/sync/tps.md
  docs/product-portal/sync/welcome.md
  website/README.md
  website/i18n/en.json
  website/siteConfig.js
Labels: review

#614 Change Deployment target to v11.0
  xcconfig/common.xcconfig
Labels: build/ios, in progress

#525 Bookmarks
  Cargo.lock
  components/places/Cargo.toml
  components/places/examples/places-utils.rs
  components/places/src/db/db.rs
  components/places/src/db/schema.rs
  components/places/src/error.rs
  components/places/src/storage/bookmarks.rs
  components/places/src/storage/mod.rs
  components/places/src/types.rs
Labels: in progress

#645 Push comms
  components/push/.gitignore
  components/push/Cargo.toml
  components/push/README.md
  components/push/android/src/main/AndroidManifest.xml
  components/push/android/src/main/java/org/mozilla/push/LibPushFFI.kt
  components/push/android/src/main/java/org/mozilla/push/PushConnection.kt
  components/push/android/src/main/java/org/mozilla/push/RustError.kt
  components/push/communications/Cargo.toml
  components/push/communications/src/lib.rs
  components/push/config/Cargo.toml
  components/push/config/src/lib.rs
  components/push/crypto/Cargo.toml
  components/push/crypto/src/lib.rs
  components/push/error/Cargo.toml
  components/push/error/src/lib.rs
  components/push/storage/Cargo.toml
  components/push/storage/src/db.rs
  components/push/storage/src/lib.rs
  components/push/subscriber/Cargo.toml
  components/push/subscriber/src/lib.rs
Labels: review

#654 add context parameter to metrics discussion
  docs/product-portal/accounts/metrics.md
Labels: review

#687 Document to need to install desktop dependencies manually.
  docs/contributing.md
  libs/bootstrap-desktop.sh
Labels: in progress
