Repository mozilla/application-services, pull requests merged in 2019-03, with the labels that each got.

#705 Update the decision_task lib/megazord list, and document its existence
  automation/taskcluster/decision_task.py
Labels: in progress, logins

#718 Refactor places connection management
  CHANGELOG.md
  components/places/android/src/main/java/org/mozilla/places/LibPlacesFFI.kt
  components/places/android/src/main/java/org/mozilla/places/PlacesConnection.kt
  components/places/android/src/test/java/org/mozilla/places/PlacesConnectionTest.kt
  components/places/benches/search.rs
  components/places/examples/autocomplete.rs
  components/places/examples/places-utils.rs
  components/places/ffi/src/lib.rs
  components/places/src/api/history.rs
  components/places/src/api/matcher.rs
  components/places/src/api/mod.rs
  components/places/src/api/places_api.rs
  components/places/src/db/db.rs
  components/places/src/db/schema.rs
  components/places/src/error.rs
  components/places/src/history_sync/store.rs
  components/places/src/lib.rs
  components/places/src/storage/bookmarks.rs
Labels: :bookmark: bookmarks, review

#725 Add the ability to update bookmarks
  components/places/src/error.rs
  components/places/src/ffi.rs
  components/places/src/storage/bookmarks.rs
Labels: :bookmark: bookmarks, in progress

#683 Add FFI descriptors (WIP)
  Cargo.lock
  Cargo.toml
  components/push/Cargo.toml
  components/push/android/build.gradle
  components/push/android/src/main/AndroidManifest.xml
  components/push/android/src/main/java/mozilla/appservices/push/LibPushFFI.kt
  components/push/android/src/main/java/mozilla/appservices/push/PushManager.kt
  components/push/android/src/main/java/mozilla/appservices/push/RustError.kt
  components/push/android/src/main/java/org/mozilla/push/PushConnection.kt
  components/push/android/src/test/java/mozilla/appservices/push/PushTest.kt
  components/push/communications/Cargo.toml
  components/push/communications/src/lib.rs
  components/push/config/Cargo.toml
  components/push/config/src/lib.rs
  components/push/crypto/Cargo.toml
  components/push/crypto/src/error.rs
  components/push/crypto/src/lib.rs
  components/push/error/Cargo.toml
  components/push/error/src/lib.rs
  components/push/ffi/Cargo.toml
  components/push/ffi/src/lib.rs
  components/push/src/lib.rs
  components/push/storage/Cargo.toml
  components/push/storage/src/db.rs
  components/push/storage/src/record.rs
  components/push/subscriber/Cargo.toml
  components/push/subscriber/src/lib.rs
  gradle-plugin/build.gradle
  gradle-plugin/src/main/kotlin/mozilla/appservices/AppServicesExtension.kt
  megazords/fenix/Cargo.toml
  megazords/fenix/android/build.gradle
  megazords/fenix/android/src/main/java/mozilla/appservices/FenixMegazord.java
  megazords/fenix/src/lib.rs
  megazords/reference-browser/Cargo.toml
  megazords/reference-browser/android/build.gradle
  megazords/reference-browser/android/src/main/java/mozilla/appservices/ReferenceBrowserMegazord.java
  megazords/reference-browser/src/lib.rs
  settings.gradle
Labels: :mega: push, in progress

#736 feat: Change "GeneralError" references to specific errors in Push Com…
  components/push/communications/src/lib.rs
  components/push/crypto/src/lib.rs
Labels: :mega: push, enhancement, review

#734 docs: Improve the README to include example calls
  components/push/README.md
Labels: WIP, review, 🤡 docs

#739 feat: expose a store helper for dispatch
  components/push/android/src/main/java/mozilla/appservices/push/LibPushFFI.kt
  components/push/android/src/main/java/mozilla/appservices/push/PushManager.kt
  components/push/android/src/test/java/mozilla/appservices/push/PushTest.kt
  components/push/ffi/src/lib.rs
  components/push/storage/src/db.rs
  components/push/storage/src/schema.sql
  components/push/subscriber/src/lib.rs
Labels: :mega: push, review

#778 Determine libs dir git SHA automatically instead of hardcoding it
  build.gradle
Labels: review

#766 Fix getWriter doc in android places
  components/places/android/src/main/java/mozilla/appservices/places/PlacesConnection.kt
Labels: review

#801 Add strace docs to fxa-dev
  docs/product-portal/accounts/local-development.md
Labels: review

#790 feat: Use temporary directory for test db
  components/push/android/src/test/java/mozilla/appservices/push/PushTest.kt
Labels: :mega: Push

#726 Use google docs for editing the component diagram in the README.
  README.md
Labels: :clown_face: docs, review

#823 Kill Sandvich, update various outdated iOS build steps, document
  .circleci/config.yml
  .gitignore
  build-carthage.sh
  docs/howtos/cut-a-new-release.md
  samples/sandvich-ios/.gitignore
  samples/sandvich-ios/Cartfile
  samples/sandvich-ios/Cartfile.resolved
  samples/sandvich-ios/Example.xcodeproj/project.pbxproj
  samples/sandvich-ios/Example.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  samples/sandvich-ios/Example.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  samples/sandvich-ios/Example/AppDelegate.swift
  samples/sandvich-ios/Example/Assets.xcassets/AppIcon.appiconset/Contents.json
  samples/sandvich-ios/Example/Assets.xcassets/Contents.json
  samples/sandvich-ios/Example/Base.lproj/LaunchScreen.storyboard
  samples/sandvich-ios/Example/Base.lproj/Main.storyboard
  samples/sandvich-ios/Example/FxAView.swift
  samples/sandvich-ios/Example/Info.plist
  samples/sandvich-ios/Example/ProfileView.swift
  samples/sandvich-ios/Example/ViewController.swift
  samples/sandvich-ios/README.md
  samples/sandvich-ios/base.xcconfig
  samples/sandvich-ios/debug.xcconfig
  samples/sandvich-ios/release.xcconfig
Labels: review
